server:
  port : 5000
  servlet:
    context-path: /audit-server
  error:
    include-message: always
spring:
  security:
    user:
      name: admin
      password: admin
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/audit"
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8