server:
  port : 5000
  servlet:
    context-path: /audit-service
  error:
    include-message: always
message:
  topic:
    name: notification
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/audit"
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8